kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: OFWwdh7fSPs4ARNacjXkm9Pr7bR+/FsgSYJ9tLT+3Vk=
      - identity: {}
