kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: DTrnSD8DWX1KSEyfmijBp6LTcyXOjHviEBI0gGlmPGY=
      - identity: {}
